---
- name: Add Ruby apt repo
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Install Packages | apt
  apt:
    state: latest
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - software-properties-common
    - python-pip
    - ruby2.0
    - git

- name: Install Packages | pip
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - awscli

- name: See if CodeDeploy Agent is installed
  stat: path=/etc/init.d/codedeploy-agent
  register: codedeploy_agent

- name: Get Instance Metadata | ec2
  action: ec2_facts
  when: codedeploy_agent.stat.exists == False

- name: Get CodeDeploy | s3
  get_url:
    url: "https://aws-codedeploy-{{ ansible_ec2_placement_region }}.s3.amazonaws.com/latest/install"
    dest: /tmp/codedeploy-install
  when: codedeploy_agent.stat.exists == False

- name: Codedeploy Install Binary | Permission Executable
  file:
    state: file
    path: /tmp/codedeploy-install
    group: www-data
    owner: www-data
    mode: 0777
  when: codedeploy_agent.stat.exists == False

- name: Codedeploy Install
  become: true
  command: /tmp/codedeploy-install auto
  when: codedeploy_agent.stat.exists == False
